# Zomato Kolkata Restaurant Analysis
### EDA Pandas & Numpy
**Tools** : Pandas , Numpy
**Dataset** : Zomato Dataset (Kaggle)

In [1]:
import pandas as pd
import numpy as np
import warnings

warnings.filterwarnings('ignore')
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 120)
print('Libraries loaded successfully')
print('Pandas  version :', pd.__version__)
print('NumPy   version :', np.__version__)

Libraries loaded successfully
Pandas  version : 3.0.1
NumPy   version : 2.4.3

In [2]:
# Little "Brain"

import os
# If we are inside the 'notebooks' folder, move the 'working directory' UP to the root
if os.path.basename(os.getcwd()) == 'notebooks':
    os.chdir('..')

# Now, you can just use 'data/Zomato_Kolkata.csv' normally!
print("Current folder:", os.getcwd())

Current folder: C:\Users\Dell\PycharmProjects\ipl-eda-analysis\notebook

## 1. Load & First Look at the Data

In [3]:
df = pd.read_csv('../data/Zomato_Kolkata.csv', encoding='latin-1')
print('Shape (rows x columns):', df.shape)
print('\nColumn Names:')
print(df.columns.tolist())

Shape (rows x columns): (7388, 7)

Column Names:
['name', 'voteCount', 'rating', 'address', 'cusine', 'cost', 'timing']

In [4]:
# First 10 rows
display(df.head(10))

,name,voteCount,rating,address,cusine,cost,timing
0,Peter Cat,12404 votes,4.2,"18A, Park Street, Park Street Area, Kolkata","North Indian, Continental","â¹1,000",11am â 11:20pm (Mon-Sun)
1,Naturals Ice Cream,2498 votes,4.9,"77/1/A, Ground Floor, Near West Bengal Board, ...","North Indian, Continental",â¹200,11am â 12midnight (Mon-Sun)
2,Carpe Diem,4083 votes,4.4,"18M, Park Street Area, Kolkata",Ice Cream,"â¹1,000","12noon â 12midnight (Mon, Tue, Wed, Thu, Fri..."
3,Barbeque Nation,5455 votes,4.6,"1st Floor, 24, Park Center Building, Park Stre...",Ice Cream,"â¹1,800","12noon â 3:30pm, 6:30pm â 10:45pm (Mon-Sun)"
4,Flurys,4709 votes,4.2,"15, Apeejay House, Park Street Area, Kolkata","Chinese, North Indian, Continental",â¹400,7:30am â 11pm (Mon-Sun)
5,KFC,2135 votes,4.1,"20K, Park Street, Park Street Area, Kolkata","Chinese, North Indian, Continental",â¹450,11am â 11pm (Mon-Sun)
6,Tung Fong,3644 votes,4.3,"25 B, Ground Floor, Karnani Mansion, Free Scho...","North Indian, Chinese, Kebab, BBQ","â¹1,000","12noon â 4pm, 6pm â 11pm (Mon-Sun)"
7,Arsalan,1500 votes,4.0,"119 A, Muzaffar Ahmed Street, Mirza Ghalib Str...","North Indian, Chinese, Kebab, BBQ","â¹1,000",11am â 11:45pm (Mon-Sun)
8,Kusum Rolls,1973 votes,4.1,"21, Karnani Mansion, Park Street Area, Kolkata","Bakery, Desserts, Sandwich",â¹300,12noon â 11pm (Mon-Sun)
9,Kareem's,1027 votes,4.3,"55 B, Mirza Ghalib Street, Park Street Area, K...","Bakery, Desserts, Sandwich","â¹1,200","12:30pm â 4:30pm, 6:30pm â 11:30pm (Mon-Sun)"

In [5]:
# Last 5 rows
df.tail()

,name,voteCount,rating,address,cusine,cost,timing
7383,WOW! ARBA,Cuisines:,NEW,Delivery Only,"Chinese, Fast Food",â¹150,11am â 11pm (Mon-Sun)
7384,Renu's,50 votes,2.8,"89/109, Vivekananda Road, Bangur Park, Hooghly...",Bengali,â¹350,11am â 11pm (Mon-Sun)
7385,The Food Place,Cuisines:,-,"119, Ramkrishna Road, Radhashree, Landmark- Ai...",Bengali,â¹150,8am â 11:45pm (Mon-Sun)
7386,New Dalma Restaurant,Cuisines:,-,Delivery Only,Chinese,â¹250,12noon â 10:30pm (Mon-Sun)
7387,Baanerjee Cabin,Cuisines:,NEW,"89, Nripen Sarkar Road, Sahapukur, Sreedurga C...",Chinese,â¹200,10am â 11pm (Mon-Sun)

In [6]:
df.shape

(7388, 7)

In [7]:
df.size

51716

In [10]:
df.columns.tolist()

['name', 'voteCount', 'rating', 'address', 'cusine', 'cost', 'timing']

In [11]:
df.index

RangeIndex(start=0, stop=7388, step=1)

In [12]:
df.dtypes

name         str
voteCount    str
rating       str
address      str
cusine       str
cost         str
timing       str
dtype: object

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7388 entries, 0 to 7387
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   name       7388 non-null   str
 1   voteCount  7388 non-null   str
 2   rating     7104 non-null   str
 3   address    7387 non-null   str
 4   cusine     7388 non-null   str
 5   cost       7387 non-null   str
 6   timing     7086 non-null   str
dtypes: str(7)
memory usage: 404.2 KB

In [14]:
df.describe(include='all')

                name  voteCount rating        address   cusine    cost                   timing
count           7388       7388   7104           7387     7388    7387                     7086
unique          6888        743     33           6926     1097      41                     1193
top     Haji Biryani  Cuisines:      -  Delivery Only  Chinese  â¹300  11am â 11pm (Mon-Sun)
freq              10       2195   1520            195      346    1362                      981

## 2. Data Cleaning

In [15]:
df.isnull()

       name  voteCount  rating  address  cusine   cost  timing
0     False      False   False    False   False  False   False
1     False      False   False    False   False  False   False
2     False      False   False    False   False  False   False
3     False      False   False    False   False  False   False
4     False      False   False    False   False  False   False
...     ...        ...     ...      ...     ...    ...     ...
7383  False      False   False    False   False  False   False
7384  False      False   False    False   False  False   False
7385  False      False   False    False   False  False   False
7386  False      False   False    False   False  False   False
7387  False      False   False    False   False  False   False

[7388 rows x 7 columns]

In [16]:
df.isnull().sum()

name           0
voteCount      0
rating       284
address        1
cusine         0
cost           1
timing       302
dtype: int64

In [17]:
df.isnull().sum().sum()

np.int64(588)

In [18]:
df.isnull().sum()[df.isnull().sum() > 0]

rating     284
address      1
cost         1
timing     302
dtype: int64

In [19]:
display(df.head(3))
display(df.tail(3))

,name,voteCount,rating,address,cusine,cost,timing
0,Peter Cat,12404 votes,4.2,"18A, Park Street, Park Street Area, Kolkata","North Indian, Continental","â¹1,000",11am â 11:20pm (Mon-Sun)
1,Naturals Ice Cream,2498 votes,4.9,"77/1/A, Ground Floor, Near West Bengal Board, ...","North Indian, Continental",â¹200,11am â 12midnight (Mon-Sun)
2,Carpe Diem,4083 votes,4.4,"18M, Park Street Area, Kolkata",Ice Cream,"â¹1,000","12noon â 12midnight (Mon, Tue, Wed, Thu, Fri..."

,name,voteCount,rating,address,cusine,cost,timing
7385,The Food Place,Cuisines:,-,"119, Ramkrishna Road, Radhashree, Landmark- Ai...",Bengali,â¹150,8am â 11:45pm (Mon-Sun)
7386,New Dalma Restaurant,Cuisines:,-,Delivery Only,Chinese,â¹250,12noon â 10:30pm (Mon-Sun)
7387,Baanerjee Cabin,Cuisines:,NEW,"89, Nripen Sarkar Road, Sahapukur, Sreedurga C...",Chinese,â¹200,10am â 11pm (Mon-Sun)

In [20]:
len(df)

7388

In [21]:
(df.isnull().sum()/len(df)*100).round(2)

name         0.00
voteCount    0.00
rating       3.84
address      0.01
cusine       0.00
cost         0.01
timing       4.09
dtype: float64

In [22]:
null_counts = df.isnull().sum()[df.isnull().sum()>0]
print(null_counts)
null_pct = (df.isnull().sum()/len(df)*100).round(2)
print(null_pct)
null_summary = pd.DataFrame({'null_count' : null_counts , 'null_percentage' : null_pct})
null_summary[null_summary['null_count'] > 0]

rating     284
address      1
cost         1
timing     302
dtype: int64
name         0.00
voteCount    0.00
rating       3.84
address      0.01
cusine       0.00
cost         0.01
timing       4.09
dtype: float64

         null_count  null_percentage
address         1.0             0.01
cost            1.0             0.01
rating        284.0             3.84
timing        302.0             4.09

In [23]:
df.duplicated().sum()

np.int64(0)

In [24]:
df.drop_duplicates(inplace = True)

In [25]:
len(df)

7388

In [26]:
df['rating'].value_counts()

rating
-      1520
3.2     538
3.3     526
3.4     476
3.1     461
3.5     438
3.0     423
3.6     417
NEW     385
3.7     338
2.9     282
3.8     259
3.9     204
4.0     156
2.8     151
4.1     119
2.7      92
4.2      72
4.3      53
2.6      49
4.4      36
2.5      25
4.6      18
2.4      18
4.5      17
2.3       9
2.2       7
4.8       6
4.7       5
4.9       1
2.1       1
1.9       1
2.0       1
Name: count, dtype: int64

In [27]:
df['rating'].value_counts().head(20)

rating
-      1520
3.2     538
3.3     526
3.4     476
3.1     461
3.5     438
3.0     423
3.6     417
NEW     385
3.7     338
2.9     282
3.8     259
3.9     204
4.0     156
2.8     151
4.1     119
2.7      92
4.2      72
4.3      53
2.6      49
Name: count, dtype: int64

In [28]:
df['rating'].value_counts().sum()

np.int64(7104)

In [29]:
df['rating'] = df['rating'].astype(str)
df['rating'] = df['rating'].str.replace('/5' , '' , regex = False).str.strip()
df['rating'] = pd.to_numeric(df['rating'], errors = 'coerce')

In [30]:
print(df['rating'])
print(df['rating'].dtypes)

0       4.2
1       4.9
2       4.4
3       4.6
4       4.2
       ...
7383    NaN
7384    2.8
7385    NaN
7386    NaN
7387    NaN
Name: rating, Length: 7388, dtype: float64
float64

In [31]:
print(df['cost'].value_counts())

cost
â¹300      1362
â¹200      1231
â¹400       795
â¹250       752
â¹500       633
â¹150       534
â¹100       426
â¹350       388
â¹600       296
â¹450       181
â¹800       156
â¹700       143
â¹1,000      88
â¹550        83
â¹650        54
â¹900        46
â¹1,200      45
â¹850        22
â¹1,500      21
â¹750        21
â¹1,100      16
â¹1,800      11
â¹1,600      11
â¹2,000      11
â¹1,300      10
â¹1,400      10
â¹4,000       7
â¹3,000       5
â¹950         5
â¹3,500       5
â¹2,100       3
â¹1,700       3
â¹1,900       2
â¹2,200       2
â¹2,600       2
â¹2,500       2
â¹3,300       1
â¹4,500       1
â¹240         1
â¹199         1
â¹160         1
Name: count, dtype: int64

In [81]:
# 1. Take the part before any brackets '(' 
df['timing'] = df['timing'].str.split('(').str[0]

# 2. The "Power Cleaner" (Regex)
# This finds anything that is NOT a letter, number, space, colon, or comma
# and replaces it with a '-' (which makes the time range look better)
df['timing'] = df['timing'].str.replace(r'[^a-zA-Z0-9\s,:]', '-', regex=True)

# 3. Clean up any double dashes or extra spaces left behind
df['timing_clean'] = df['timing'].str.replace('-+', '-', regex=True).str.strip()

# 4. Check the results
display(df['timing_clean'].head(10))

0                        11am - 11:20pm
1                     11am - 12midnight
2                   12noon - 12midnight
3     12noon - 3:30pm, 6:30pm - 10:45pm
4                         7:30am - 11pm
5                           11am - 11pm
6              12noon - 4pm, 6pm - 11pm
7                        11am - 11:45pm
8                         12noon - 11pm
9    12:30pm - 4:30pm, 6:30pm - 11:30pm
Name: timing_clean, dtype: object

In [32]:
# 1.
df['cost'] = df['cost'].astype(str)

# 2. Clean EVERYTHING that isn't a number (removes ₹, commas, and weird symbols)
df['cost'] = df['cost'].str.replace(r'[^0-9]', '', regex=True)

print(df['cost'])

# 3. Convert to numeric
df['cost'] = pd.to_numeric(df['cost'], errors='coerce')

print(df['cost'])

# 4. Rename it ONLY after cleaning is successful
df.rename(columns={'cost': 'cost_for_two'}, inplace=True)

# 5. Check it immediately
display(df[['name', 'cost_for_two']].head())

0       1000
1        200
2       1000
3       1800
4        400
        ...
7383     150
7384     350
7385     150
7386     250
7387     200
Name: cost, Length: 7388, dtype: str
0       1000.0
1        200.0
2       1000.0
3       1800.0
4        400.0
         ...
7383     150.0
7384     350.0
7385     150.0
7386     250.0
7387     200.0
Name: cost, Length: 7388, dtype: float64

                 name  cost_for_two
0           Peter Cat        1000.0
1  Naturals Ice Cream         200.0
2          Carpe Diem        1000.0
3     Barbeque Nation        1800.0
4              Flurys         400.0

In [33]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7388 entries, 0 to 7387
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   name          7388 non-null   str
 1   voteCount     7388 non-null   str
 2   rating        5199 non-null   float64
 3   address       7387 non-null   str
 4   cusine        7388 non-null   str
 5   cost_for_two  7387 non-null   float64
 6   timing        7086 non-null   str
dtypes: float64(2), str(5)
memory usage: 404.2 KB

In [34]:
print(df.columns.to_list())
print(list(df.columns))
print(df['cost_for_two'].describe())

['name', 'voteCount', 'rating', 'address', 'cusine', 'cost_for_two', 'timing']
['name', 'voteCount', 'rating', 'address', 'cusine', 'cost_for_two', 'timing']
count    7387.000000
mean      373.263707
std       296.071205
min       100.000000
25%       200.000000
50%       300.000000
75%       450.000000
max      4500.000000
Name: cost_for_two, dtype: float64

In [35]:
len(df)

7388

In [36]:
df.isnull().sum()

name               0
voteCount          0
rating          2189
address            1
cusine             0
cost_for_two       1
timing           302
dtype: int64

In [37]:
df.head(20)

,name,voteCount,rating,address,cusine,cost_for_two,timing
0,Peter Cat,12404 votes,4.2,"18A, Park Street, Park Street Area, Kolkata","North Indian, Continental",1000.0,11am â 11:20pm (Mon-Sun)
1,Naturals Ice Cream,2498 votes,4.9,"77/1/A, Ground Floor, Near West Bengal Board, ...","North Indian, Continental",200.0,11am â 12midnight (Mon-Sun)
2,Carpe Diem,4083 votes,4.4,"18M, Park Street Area, Kolkata",Ice Cream,1000.0,"12noon â 12midnight (Mon, Tue, Wed, Thu, Fri..."
3,Barbeque Nation,5455 votes,4.6,"1st Floor, 24, Park Center Building, Park Stre...",Ice Cream,1800.0,"12noon â 3:30pm, 6:30pm â 10:45pm (Mon-Sun)"
4,Flurys,4709 votes,4.2,"15, Apeejay House, Park Street Area, Kolkata","Chinese, North Indian, Continental",400.0,7:30am â 11pm (Mon-Sun)
5,KFC,2135 votes,4.1,"20K, Park Street, Park Street Area, Kolkata","Chinese, North Indian, Continental",450.0,11am â 11pm (Mon-Sun)
6,Tung Fong,3644 votes,4.3,"25 B, Ground Floor, Karnani Mansion, Free Scho...","North Indian, Chinese, Kebab, BBQ",1000.0,"12noon â 4pm, 6pm â 11pm (Mon-Sun)"
7,Arsalan,1500 votes,4.0,"119 A, Muzaffar Ahmed Street, Mirza Ghalib Str...","North Indian, Chinese, Kebab, BBQ",1000.0,11am â 11:45pm (Mon-Sun)
8,Kusum Rolls,1973 votes,4.1,"21, Karnani Mansion, Park Street Area, Kolkata","Bakery, Desserts, Sandwich",300.0,12noon â 11pm (Mon-Sun)
9,Kareem's,1027 votes,4.3,"55 B, Mirza Ghalib Street, Park Street Area, K...","Bakery, Desserts, Sandwich",1200.0,"12:30pm â 4:30pm, 6:30pm â 11:30pm (Mon-Sun)"
10,WOW! China,53 votes,3.8,"19-57, Park Street Area, Kolkata","Fast Food, Burger",650.0,12noon â 11pm (Mon-Sun)
11,Golden Spoon,1000 votes,3.6,"1, Middleton Row, Near Loreto House, Park Stre...","Fast Food, Burger",600.0,12noon â 11pm (Mon-Sun)
12,BarBQ,8321 votes,4.3,"43-47-55, Park Street Area, Kolkata","Chinese, Asian",1200.0,12noon â 11:15pm (Mon-Sun)
13,The Kebab Factory,Cuisines:,NaN,"33, Royd Street, Park Street Area, Kolkata","Chinese, Asian",350.0,11am â 11pm (Mon-Sun)
14,Patisserie By Franziska,Cuisines:,NaN,"13C, Russell Street, Opposite Bengal Club, Par...","Mughlai, North Indian, Rolls, Biryani",450.0,NaN
15,The Sixth Sense,92 votes,4.0,"25B, Karnani Mansion, Opposite Westside, Park ...","Mughlai, North Indian, Rolls, Biryani",1500.0,"12noon â 12midnight (Mon-Thu),12noon â 2am..."
16,Food King,23 votes,3.3,"90/1, Ground Floor, Muzaffar Ahmed Street, War...",Rolls,300.0,12noon â 11:30pm (Mon-Sun)
17,Burgrill,888 votes,4.2,"12B/2, Park Street Park, Opposite Oxford Book ...",Rolls,500.0,11am â 2am (Mon-Sun)
18,Zainab Biryani,Cuisines:,NaN,"19, Alimuddin Street, Park Street Area, Kolkata","Biryani, North Indian, Mughlai",400.0,11am â 11pm (Mon-Sun)
19,The Crepe Cafe,81 votes,4.4,"6/1A, Middleton Street, Park Street Area, Kolkata","Biryani, North Indian, Mughlai",800.0,10:30am â 10:30pm (Mon-Sun)

In [38]:
df.describe(include='all')

                name  voteCount       rating        address   cusine  cost_for_two                   timing
count           7388       7388  5199.000000           7387     7388   7387.000000                     7086
unique          6888        743          NaN           6926     1097           NaN                     1193
top     Haji Biryani  Cuisines:          NaN  Delivery Only  Chinese           NaN  11am â 11pm (Mon-Sun)
freq              10       2195          NaN            195      346           NaN                      981
mean             NaN        NaN     3.389075            NaN      NaN    373.263707                      NaN
std              NaN        NaN     0.405356            NaN      NaN    296.071205                      NaN
min              NaN        NaN     1.900000            NaN      NaN    100.000000                      NaN
25%              NaN        NaN     3.100000            NaN      NaN    200.000000                      NaN
50%              NaN        NaN     3.400000            NaN      NaN    300.000000                      NaN
75%              NaN        NaN     3.600000            NaN      NaN    450.000000                      NaN
max              NaN        NaN     4.900000            NaN      NaN   4500.000000                      NaN

In [39]:
#display(df[df['rating'].isnull()])
# The "any" part means "if at least one of these is True"
display(df[df[['rating', 'timing']].isnull().any(axis=1)])

,name,voteCount,rating,address,cusine,cost_for_two,timing
13,The Kebab Factory,Cuisines:,NaN,"33, Royd Street, Park Street Area, Kolkata","Chinese, Asian",350.0,11am â 11pm (Mon-Sun)
14,Patisserie By Franziska,Cuisines:,NaN,"13C, Russell Street, Opposite Bengal Club, Par...","Mughlai, North Indian, Rolls, Biryani",450.0,NaN
18,Zainab Biryani,Cuisines:,NaN,"19, Alimuddin Street, Park Street Area, Kolkata","Biryani, North Indian, Mughlai",400.0,11am â 11pm (Mon-Sun)
31,Aqua - The Park,801 votes,4.0,"The Park, 17, Park Street Area, Kolkata","Continental, Chinese, North Indian",3000.0,NaN
33,Paradise Biryani,Cuisines:,NaN,"Shop 30 D, Ground Floor, Building Chowringhee ...","Chinese, Fast Food",800.0,11am â 11pm (Mon-Sun)
...,...,...,...,...,...,...,...
7382,Shanta's Kitchen,Cuisines:,NaN,"Village Jugberia, New Barrakpur, Barasat, Kolkata","Chinese, Fast Food",400.0,6:30am â 10pm (Mon-Sun)
7383,WOW! ARBA,Cuisines:,NaN,Delivery Only,"Chinese, Fast Food",150.0,11am â 11pm (Mon-Sun)
7385,The Food Place,Cuisines:,NaN,"119, Ramkrishna Road, Radhashree, Landmark- Ai...",Bengali,150.0,8am â 11:45pm (Mon-Sun)
7386,New Dalma Restaurant,Cuisines:,NaN,Delivery Only,Chinese,250.0,12noon â 10:30pm (Mon-Sun)
7387,Baanerjee Cabin,Cuisines:,NaN,"89, Nripen Sarkar Road, Sahapukur, Sreedurga C...",Chinese,200.0,10am â 11pm (Mon-Sun)

In [40]:
display(df[df['timing'].isnull()])

,name,voteCount,rating,address,cusine,cost_for_two,timing
14,Patisserie By Franziska,Cuisines:,NaN,"13C, Russell Street, Opposite Bengal Club, Par...","Mughlai, North Indian, Rolls, Biryani",450.0,NaN
31,Aqua - The Park,801 votes,4.0,"The Park, 17, Park Street Area, Kolkata","Continental, Chinese, North Indian",3000.0,NaN
39,Sienna Store & Cafe,Cuisines:,NaN,"24, 1st Floor, Development House, Park Street ...",Cafe,900.0,NaN
41,Zen - The Park,366 votes,4.1,"The Park, 17, Park Street Area, Kolkata","Desserts, Bakery, Beverages",4000.0,NaN
46,Saffron - The Park,355 votes,4.1,"The Park, 17, Park Street Area, Kolkata","Pizza, Desserts, Fast Food",1900.0,NaN
...,...,...,...,...,...,...,...
7358,Ramjee Biryaniwala And Ahuna Mutton,Cuisines:,NaN,"Akandakeshari Road, Near Akandakeshari Police ...",Chinese,300.0,NaN
7373,Rasana Tripti,Cuisines:,NaN,"12, Mahesh Colony, Nistarini Super Market, She...",Fast Food,500.0,NaN
7375,Jabbrr Afghani,121 votes,3.8,"Block GP,Near RDB Cinemas, Sector 5, Salt Lake","Chinese, Rolls, North Indian",350.0,NaN
7376,Jabbrr Afghani,203 votes,3.9,"J1/16, Ground Floor, Shaila Towers, EP Block, ...",Mishti,350.0,NaN
7380,New Dalma Restaurant,Cuisines:,NaN,"Near Ram Grocery Shop, Gouranga Nagar, Auto St...",Biryani,300.0,NaN

In [41]:
df['rating'].unique()

array([4.2, 4.9, 4.4, 4.6, 4.1, 4.3, 4. , 3.8, 3.6, nan, 3.3, 3.7, 3.9,
       3.5, 3.2, 3.1, 3. , 2.9, 3.4, 2.3, 4.5, 2.8, 4.7, 2.7, 2.6, 2.5,
       2.1, 4.8, 2.4, 2.2, 1.9, 2. ])

In [42]:
df['timing'].unique()

<StringArray>
[                        '11am â 11:20pm (Mon-Sun)',                      '11am â 12midnight (Mon-Sun)',
  '12noon â 12midnight (Mon, Tue, Wed, Thu, Fri...',    '12noon â 3:30pm, 6:30pm â 10:45pm (Mon-Sun)',
                          '7:30am â 11pm (Mon-Sun)',                            '11am â 11pm (Mon-Sun)',
             '12noon â 4pm, 6pm â 11pm (Mon-Sun)',                         '11am â 11:45pm (Mon-Sun)',
                          '12noon â 11pm (Mon-Sun)',   '12:30pm â 4:30pm, 6:30pm â 11:30pm (Mon-Sun)',
 ...
            'Closed (Mon-Fri),8am â 11pm (Sat-Sun)',         '10am â 2:30pm, 5:30pm â 10pm (Mon-Sun)',
          '6pm â 11pm (Mon-Sat),5pm â 11pm (Sun)',   '5pm â 10pm (Mon-Fri),5pm â 10:30pm (Sat-Sun)',
 '10:30am â 10pm (Mon-Fri),10am â 10pm (Sat-Sun)',   '9am â 10:30pm (Mon-Thu),9am â 11pm (Fri-Sun)',
                '8am â 3pm, 5pm â 11pm (Mon-Sun)',                '9am â 4pm, 7pm â 10pm (Mon-Sun)',
                              '7am â 7pm (Mon-Sun)',                          '8am â 11:45pm (Mon-Sun)']
Length: 1194, dtype: str

In [43]:
print(df['voteCount'].unique())
print(df['voteCount'].value_counts())

<StringArray>
['12404 votes',  '2498 votes',  '4083 votes',  '5455 votes',  '4709 votes',  '2135 votes',  '3644 votes',
  '1500 votes',  '1973 votes',  '1027 votes',
 ...
   '474 votes',   '338 votes',   '342 votes',   '499 votes',   '387 votes',  '1401 votes',   '900 votes',
   '400 votes',   '892 votes',   '571 votes']
Length: 743, dtype: str
voteCount
Cuisines:     2195
4 votes        210
6 votes        190
7 votes        182
5 votes        167
              ...
1401 votes       1
900 votes        1
400 votes        1
892 votes        1
571 votes        1
Name: count, Length: 743, dtype: int64

In [44]:
# This shows rows where BOTH are missing
both_nan = df[df[['rating', 'timing']].isnull().all(axis=1)]
display(both_nan)
print(len(both_nan))

,name,voteCount,rating,address,cusine,cost_for_two,timing
14,Patisserie By Franziska,Cuisines:,NaN,"13C, Russell Street, Opposite Bengal Club, Par...","Mughlai, North Indian, Rolls, Biryani",450.0,NaN
39,Sienna Store & Cafe,Cuisines:,NaN,"24, 1st Floor, Development House, Park Street ...",Cafe,900.0,NaN
58,Wabi Sabi,Cuisines:,NaN,"24, 1st Floor, Anuj Chambers, Park Street Area...","Continental, Seafood, Italian, North Indian",950.0,NaN
64,Sams Pub,Cuisines:,NaN,"13D, Park Street, Park Street Area, Kolkata","Rolls, Chinese, Fast Food",1000.0,NaN
124,The Food Corner,Cuisines:,NaN,"1, Waliullah Lane, Park Street Area, Kolkata","Chinese, North Indian, Continental",150.0,NaN
...,...,...,...,...,...,...,...
7352,Aayushi Food Zone,Cuisines:,NaN,"172, R.N Avenue, Rathindra Cinema, Sodepur, Ko...",South Indian,250.0,NaN
7356,The Sheherwali,Cuisines:,NaN,"Unitech Gate 1, DJ Block, Newtown, Kolkata",North Indian,300.0,NaN
7358,Ramjee Biryaniwala And Ahuna Mutton,Cuisines:,NaN,"Akandakeshari Road, Near Akandakeshari Police ...",Chinese,300.0,NaN
7373,Rasana Tripti,Cuisines:,NaN,"12, Mahesh Colony, Nistarini Super Market, She...",Fast Food,500.0,NaN
7380,New Dalma Restaurant,Cuisines:,NaN,"Near Ram Grocery Shop, Gouranga Nagar, Auto St...",Biryani,300.0,NaN

286

In [45]:
# Step 5 — Drop rows where key columns are still null after cleaning
rows_before = len(df)
df.dropna(subset=['rating', 'cost_for_two', 'address', 'cusine'], inplace=True)
rows_after  = len(df)

print('Rows before dropping nulls :', rows_before)
print('Rows after  dropping nulls :', rows_after)
print('Rows removed               :', rows_before - rows_after)
print('\nDataset is clean and ready for analysis.')

Rows before dropping nulls : 7388
Rows after  dropping nulls : 5198
Rows removed               : 2190

Dataset is clean and ready for analysis.

## 3. Area Analysis — Where are restaurants concentrated?
*Using Pandas value_counts, groupby, sort_values*

In [61]:
# Q1 — Top 12 areas by number of restaurants

top_locations = df['address'].value_counts().head(12).reset_index()
print(top_locations)
top_locations.columns = ['area', 'restaurant_count']
top_locations['percentage'] = (top_locations['restaurant_count'] / len(df) * 100).round(1)
print(top_locations.to_string(index=False))
print('\nTop area:', top_locations['area'].iloc[0],
      'with', top_locations['restaurant_count'].iloc[0], 'restaurants')

                                              address  count
0                                       Delivery Only     84
1   35/1, AJC Bose Road, Near Mercy Hospital, Park...      6
2   Ffort Raichak, Post Bag 1, Sarisa, South 24 Pa...      6
3   33/1A, 4th Floor, Pantaloons, Upendra Chandra ...      5
4   ITC Sonar, JBS Haldane Avenue, EM Bypass, Scie...      4
5   32, 3rd Floor, Avani Riverside Mall, Jagat Ban...      4
6   ITC Royal Bengal, JBS Haldane Avenue, EM Bypas...      4
7             The Park, 17, Park Street Area, Kolkata      3
8                     57 A, Park Street Area, Kolkata      3
9     42A, Rawdon Street, Loudon Street Area, Kolkata      3
10  Lytton Hotel, 14 & 14/1, Sudder Street, New Ma...      3
11                31, Sarat Bose Road, Elgin, Kolkata      3
                                                                             area  restaurant_count  percentage
                                                                    Delivery Only                84         1.6
              35/1, AJC Bose Road, Near Mercy Hospital, Park Street Area, Kolkata                 6         0.1
             Ffort Raichak, Post Bag 1, Sarisa, South 24 Parganas, Falta, Kolkata                 6         0.1
33/1A, 4th Floor, Pantaloons, Upendra Chandra Banerjee Road, Kankurgachi, Kolkata                 5         0.1
             ITC Sonar, JBS Haldane Avenue, EM Bypass, Science City Area, Kolkata                 4         0.1
   32, 3rd Floor, Avani Riverside Mall, Jagat Banerjee Ghat Road, Shibpur, Howrah                 4         0.1
      ITC Royal Bengal, JBS Haldane Avenue, EM Bypass, Science City Area, Kolkata                 4         0.1
                                          The Park, 17, Park Street Area, Kolkata                 3         0.1
                                                  57 A, Park Street Area, Kolkata                 3         0.1
                                  42A, Rawdon Street, Loudon Street Area, Kolkata                 3         0.1
                 Lytton Hotel, 14 & 14/1, Sudder Street, New Market Area, Kolkata                 3         0.1
                                              31, Sarat Bose Road, Elgin, Kolkata                 3         0.1

Top area: Delivery Only with 84 restaurants

In [63]:
# Q2 — Average rating by area (Pandas groupby + agg)

# Step 1: Clean columns to numbers (Crucial or mean() will fail)
df['rating'] = pd.to_numeric(df['rating'], errors='coerce')
df['cost_for_two'] = pd.to_numeric(df['cost_for_two'], errors='coerce')

# Step 2: Group and Aggregate
# We use a dictionary to tell Pandas exactly what to do with each column
area_stats = df.groupby('address').agg(
    total_restaurants = ('name', 'count'),
    avg_rating        = ('rating', 'mean'),
    avg_cost          = ('cost_for_two', 'mean'),
    total_votes       = ('voteCount', 'sum')
).reset_index()

print(area_stats)

print(area_stats.info())

# Step 3: Clean the results (Rounding)
area_stats['avg_rating'] = area_stats['avg_rating'].round(2)
area_stats['avg_cost']   = area_stats['avg_cost'].fillna(0).astype(int)

print(area_stats)

print(area_stats.info())


# Step 4: Filter and Sort
area_stats = area_stats[area_stats['total_restaurants'] >=3]
area_stats = area_stats.sort_values('avg_rating', ascending=False)

# Step 5: Display
display(area_stats.head(20))

                                                address  total_restaurants  avg_rating  avg_cost  total_votes
0     1 2nd Floor, Ward No-70, Allennby Road, BR VII...                  1    3.500000     600.0         28.0
1                  1 A, Southend Park, Golpark, Kolkata                  1    3.800000     450.0         33.0
2     1 Kodaliya Gram Panchayat Chisurah Station Roa...                  1    3.200000     200.0          7.0
3       1 West Range, Ground Floor, Ballygunge, Kolkata                  1    3.900000     300.0        275.0
4             1, A.J.C. Bose Road, Chowringhee, Kolkata                  3    3.733333     300.0        407.0
...                                                 ...                ...         ...       ...          ...
4927  Ward 66 2/1, Chowbaga Road, Picnic Garden, Kol...                  1    3.100000     350.0          4.0
4928  West Beraberi, Narayanpur, Paschim, Rajarhat, ...                  1    3.200000     300.0          9.0
4929  Wireless More, North 24 Parganas, Barrackpore,...                  1    3.300000     600.0         18.0
4930  Yuvak Sangh Building, Station Road, Nabagram, ...                  1    3.400000     300.0         38.0
4931  Z3/34/1/E, Dr. Abdul Kabir Road, Kidderpore, K...                  1    3.100000     300.0          6.0

[4932 rows x 5 columns]
<class 'pandas.DataFrame'>
RangeIndex: 4932 entries, 0 to 4931
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   address            4932 non-null   str
 1   total_restaurants  4932 non-null   int64
 2   avg_rating         4932 non-null   float64
 3   avg_cost           4932 non-null   float64
 4   total_votes        4932 non-null   float64
dtypes: float64(3), int64(1), str(1)
memory usage: 192.8 KB
None
                                                address  total_restaurants  avg_rating  avg_cost  total_votes
0     1 2nd Floor, Ward No-70, Allennby Road, BR VII...                  1        3.50       600         28.0
1                  1 A, Southend Park, Golpark, Kolkata                  1        3.80       450         33.0
2     1 Kodaliya Gram Panchayat Chisurah Station Roa...                  1        3.20       200          7.0
3       1 West Range, Ground Floor, Ballygunge, Kolkata                  1        3.90       300        275.0
4             1, A.J.C. Bose Road, Chowringhee, Kolkata                  3        3.73       300        407.0
...                                                 ...                ...         ...       ...          ...
4927  Ward 66 2/1, Chowbaga Road, Picnic Garden, Kol...                  1        3.10       350          4.0
4928  West Beraberi, Narayanpur, Paschim, Rajarhat, ...                  1        3.20       300          9.0
4929  Wireless More, North 24 Parganas, Barrackpore,...                  1        3.30       600         18.0
4930  Yuvak Sangh Building, Station Road, Nabagram, ...                  1        3.40       300         38.0
4931  Z3/34/1/E, Dr. Abdul Kabir Road, Kidderpore, K...                  1        3.10       300          6.0

[4932 rows x 5 columns]
<class 'pandas.DataFrame'>
RangeIndex: 4932 entries, 0 to 4931
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   address            4932 non-null   str
 1   total_restaurants  4932 non-null   int64
 2   avg_rating         4932 non-null   float64
 3   avg_cost           4932 non-null   int64
 4   total_votes        4932 non-null   float64
dtypes: float64(2), int64(2), str(1)
memory usage: 192.8 KB
None

                                                address  total_restaurants  avg_rating  avg_cost  total_votes
1927                31, Sarat Bose Road, Elgin, Kolkata                  3        4.57       433        565.0
4068  ITC Sonar, JBS Haldane Avenue, EM Bypass, Scie...                  4        4.28      3500       2736.0
2742                    57 A, Park Street Area, Kolkata                  3        4.23       700       1197.0
4890  The Oberoi Grand, 15, Jawaharlal Nehru Road, N...                  3        4.17      3600        919.0
4891            The Park, 17, Park Street Area, Kolkata                  3        4.07      2966       1522.0
2374    42A, Rawdon Street, Loudon Street Area, Kolkata                  3        3.87       200       1669.0
1740                  29, 1st Lane, Ballygunge, Kolkata                  3        3.80       366        124.0
1053                19, Gariahat Road, Golpark, Kolkata                  3        3.77       183        381.0
4             1, A.J.C. Bose Road, Chowringhee, Kolkata                  3        3.73       300        407.0
4158  Lytton Hotel, 14 & 14/1, Sudder Street, New Ma...                  3        3.70      1100        279.0
287   108, Aurobindo Sarani, 4 Point Crossing, Near ...                  3        3.60       566        968.0
4066  ITC Royal Bengal, JBS Haldane Avenue, EM Bypas...                  4        3.58      3250        657.0
1804  2nd Floor, Hangout Food Court, City Center 2, ...                  3        3.57       350        130.0
3885  Ffort Raichak, Post Bag 1, Sarisa, South 24 Pa...                  6        3.57      1483        358.0
2997        6A, Muzaffar Ahmed Street, Taltala, Kolkata                  3        3.53       266       1284.0
1953  32, 3rd Floor, Avani Riverside Mall, Jagat Ban...                  4        3.47       687        846.0
2073  35/1, AJC Bose Road, Near Mercy Hospital, Park...                  6        3.43       316       1013.0
3823                                      Delivery Only                 84        3.35       316       3792.0
3133  78/79, Hari Mohan Bose Road, Howrah Station Ar...                  3        3.30       366        248.0
1255  20, Ganesh Chandra Avenue, Chandni Chowk, Kolkata                  3        3.20       516        293.0

## 4. Cuisine Analysis — What does Kolkata love to eat?
*Using Pandas str.split, explode, value_counts*

In [158]:
# Q3 — Top cuisines
# Each restaurant may list multiple cuisines: 'North Indian, Chinese, Biryani'
# explode splits each into its own row — powerful Pandas technique

cusine_series = (
    df['cusine']
    .dropna()
    .str.split(',')
    .explode()
    .str.strip()
)

top_cusines = cusine_series.value_counts().head(20).reset_index()
top_cusines.columns = ['cusine', 'restaurant_count']
top_cusines['percentage'] = (top_cusines['restaurant_count']
                               / len(df) * 100).round(1)

print('=== TOP 15 CUISINES IN KOLKATA ===')
print(top_cusines.to_string(index=False))
print('\nMost popular cuisine:', top_cusines['cusine'].iloc[0])

=== TOP 15 CUISINES IN KOLKATA ===
      cusine  restaurant_count  percentage
     Chinese              2144        41.2
North Indian              1826        35.1
   Fast Food              1305        25.1
     Biryani               672        12.9
     Bengali               488         9.4
   Beverages               471         9.1
       Rolls               387         7.4
     Mughlai               378         7.3
    Desserts               341         6.6
      Mishti               313         6.0
 Continental               306         5.9
South Indian               286         5.5
 Street Food               285         5.5
      Bakery               281         5.4
        Cafe               202         3.9
     Italian               202         3.9
     Seafood               183         3.5
       Momos               159         3.1
    Sandwich               156         3.0
      Burger               117         2.3

Most popular cuisine: Chinese

In [157]:
# Q4 Unique Restaurants

# 1. Count how many UNIQUE restaurants you have in total
total_unique_restaurants = df['name'].nunique() 

# 2. Get your top 15 cuisines
top_cuisines = cusine_series.value_counts().head(15).reset_index()
top_cuisines.columns = ['cuisine', 'restaurant_count']

# 3. Calculate percentage based on the UNIQUE total
top_cuisines['percentage'] = (top_cuisines['restaurant_count'] / total_unique_restaurants * 100).round(1)

print(f'Total Unique Restaurants in Data: {total_unique_restaurants}')
print(top_cuisines.to_string(index=False))

Total Unique Restaurants in Data: 4949
     cuisine  restaurant_count  percentage
     Chinese              2144        43.3
North Indian              1826        36.9
   Fast Food              1305        26.4
     Biryani               672        13.6
     Bengali               488         9.9
   Beverages               471         9.5
       Rolls               387         7.8
     Mughlai               378         7.6
    Desserts               341         6.9
      Mishti               313         6.3
 Continental               306         6.2
South Indian               286         5.8
 Street Food               285         5.8
      Bakery               281         5.7
        Cafe               202         4.1

## 5. Cost Analysis — What does dining in Kolkata cost?
*Using Pandas cut, qcut for binning + groupby*

In [115]:
# Q5 — Cost distribution using Pandas cut (binning)

bins = [0, 300, 800, 1500, 3000, 5000, 99999]
labels = ['Under 300', '301-800', '801-1500', 
          '1501-3000', '3001-5000', 'Above 5000']

df['cost_category'] = pd.cut(df['cost_for_two'],
                             bins=bins,
                             labels=labels)

# Use value_counts() WITHOUT sort - it auto-sorts by count
cost_dist = df['cost_category'].value_counts().reset_index()
cost_dist.columns = ['cost_range', 'restaurants']
cost_dist['percentage'] = (cost_dist['restaurants'] / len(df) * 100).round(1)

# Sort by the category ORDER (not by count)
cost_dist['cost_range'] = pd.Categorical(cost_dist['cost_range'], 
                                         categories=labels, 
                                         ordered=True)
cost_dist = cost_dist.sort_values('cost_range')

print("\n=== COST DISTRIBUTION (for two people) ===")
print(cost_dist.to_string(index=False))

=== COST DISTRIBUTION (for two people) ===
cost_range  restaurants  percentage
 Under 300         2675        51.5
   301-800         2230        42.9
  801-1500          231         4.4
 1501-3000           48         0.9
 3001-5000           14         0.3
Above 5000            0         0.0

In [116]:
# Q6 — Cost vs Rating: does spending more mean better food?
# A. Ensure columns are definitely numbers
df['rating'] = pd.to_numeric(df['rating'], errors='coerce')
# 1. Remove commas and spaces just in case
df['voteCount'] = df['voteCount'].astype(str).str.replace('votes', '').str.strip()


# 2. Force to numbers (turns "garbage" text into empty NaN)
df['voteCount'] = pd.to_numeric(df['voteCount'], errors='coerce')

# 3. Fill true missing values with 0 so the sum/mean works
df['voteCount'] = df['voteCount'].fillna(0)

# Now check the data types - voteCount should be float64 or int64
print(df['voteCount'].dtype)

# B. Run the Groupby
cost_rating = (
    df.groupby('cost_category', observed=True)
    .agg(
        restaurants = ('name', 'count'),
        avg_rating  = ('rating', 'mean'),
        avg_votes   = ('voteCount', 'mean')
    )
    .reset_index()
)

# C. Clean up the result (Handle NaNs before converting to int)
cost_rating['avg_rating'] = cost_rating['avg_rating'].round(2)
cost_rating['avg_votes']  = cost_rating['avg_votes'].fillna(0).astype(int)

print('=== DOES HIGHER COST MEAN BETTER RATING? ===')
print(cost_rating.to_string(index=False))

float64
=== DOES HIGHER COST MEAN BETTER RATING? ===
cost_category  restaurants  avg_rating  avg_votes
    Under 300         2675        3.29         65
      301-800         2230        3.45        188
     801-1500          231        3.75        665
    1501-3000           48        3.93       1122
    3001-5000           14        3.98        324

## 7. Votes Analysis — Which restaurants are most popular?
*Using Pandas sort_values, nlargest, rank*

In [52]:
# Q7 — Top 15 most voted restaurants in Kolkata
top_voted = (
    df[['name', 'address', 'rating', 'voteCount', 'cost_for_two', 'cusine']]
    .nlargest(15, 'voteCount')
    .reset_index(drop=True)
)
top_voted.index = top_voted.index + 1   # rank starts from 1

print('=== TOP 15 MOST POPULAR RESTAURANTS (by votes) ===')
print(top_voted[['name', 'address', 'rating',
                  'voteCount', 'cost_for_two']].to_string())

=== TOP 15 MOST POPULAR RESTAURANTS (by votes) ===
                              name                                                                             address  rating  voteCount  cost_for_two
1                        Peter Cat                                         18A, Park Street, Park Street Area, Kolkata     4.2    12404.0        1000.0
2                            BarBQ                                                 43-47-55, Park Street Area, Kolkata     4.3     8321.0        1200.0
3                  Barbeque Nation                      1st Floor, 24, Park Center Building, Park Street Area, Kolkata     4.6     5455.0        1800.0
4                           Hatari                 113/1B, Rash Behari Avenue, Near Triangular Park, Gariahat, Kolkata     4.4     4893.0         850.0
5                           Flurys                                        15, Apeejay House, Park Street Area, Kolkata     4.2     4709.0         400.0
6                 India Restaurant                                           34, Karl Marx Sarani, Kidderpore, Kolkata     4.5     4662.0         800.0
7   JW Kitchen - JW Marriott Hotel             JW Marriott Hotel, 4A, J.B.S Haldane Avenue, Science City Area, Kolkata     4.4     4623.0        3000.0
8                        Oudh 1590                        Shop CD 86, Sector 1, Near Seva Hospital, Salt Lake, Kolkata     4.3     4434.0        1200.0
9                       Carpe Diem                                                      18M, Park Street Area, Kolkata     4.4     4083.0        1000.0
10             Chili's Grill & Bar                    375, 2nd Floor, South City Mall, Prince Anwar Shah Road, Kolkata     4.6     3945.0        1200.0
11                    Cafe Mezzuna                             10/3, 4th Floor, Forum Mall, Elgin Road, Elgin, Kolkata     4.5     3763.0        1600.0
12              6 Ballygunge Place                                            6, Ballygunge Place, Ballygunge, Kolkata     4.4     3750.0         700.0
13                       Tung Fong  25 B, Ground Floor, Karnani Mansion, Free School Street, Park Street Area, Kolkata     4.3     3644.0        1000.0
14                            Haka                 164/1, 4th Floor, Mani Square Mall, EM Bypass, Kankurgachi, Kolkata     4.3     3534.0         700.0
15             Sigree Global Grill              1st Floor, Silver Spring Arcade, EM Bypass, Science City Area, Kolkata     4.3     3379.0        1800.0

In [98]:
# Q8 — Hidden gems: High rating but low votes
# These are underrated restaurants worth visiting
df['vote_rank']   = df['voteCount'].rank(pct=True, method='dense').round(2)
df['rating_rank'] = df['rating'].rank(pct=True, method='dense').round(2)

hidden_gems = df[
    (df['rating_rank'] >= 0.80) &   # top 20% by rating
    (df['vote_rank']   <= 0.30)      # bottom 30% by votes
][['name', 'address', 'rating', 'voteCount', 'cost_for_two', 'cusine']]

hidden_gems = hidden_gems.sort_values('rating', ascending=False).head(150)
hidden_gems = hidden_gems.reset_index(drop=True)
hidden_gems.index = hidden_gems.index + 1
print(f"Total Hidden Gems found: {len(hidden_gems)}")
print('=== HIDDEN GEMS — High Rated, Low Votes ===')
print(hidden_gems[['name', 'address', 'rating',
                    'voteCount', 'cost_for_two',]].to_string())

Total Hidden Gems found: 36
=== HIDDEN GEMS — High Rated, Low Votes ===
                              name                                                                         address  rating  voteCount  cost_for_two
1                           7 Days                            GD 151, Near GD Market, Sector 3, Salt Lake, Kolkata     4.8      118.0         500.0
2                The Shake Factory                                             31, Sarat Bose Road, Elgin, Kolkata     4.7      143.0         400.0
3                       Mach Magic                                         61, Ballygunge Garden, Golpark, Kolkata     4.7      170.0         400.0
4                Fries Before Guys                                             31, Sarat Bose Road, Elgin, Kolkata     4.6      184.0         400.0
5                 Bangla Misti Hub                                        Eco Park Gate 3, AA 2, New Town, Kolkata     4.6      220.0         500.0
6                          Siracha                   1/266, Baishnabghata Patuli Township, Block N, Garia, Kolkata     4.6       52.0         350.0
7          Veerji Malai Chaap Wale                                            AE-345, Sector 1, Salt Lake, Kolkata     4.6      167.0         500.0
8                     Roll Capital                                        57A, Sammilani Park, Ajoy Nagar, Kolkata     4.6       62.0         300.0
9                       My Hangout                                      47B, Lake Avenue, Southern Avenue, Kolkata     4.6      142.0        1100.0
10                     Monkey Chef                                    14B, Lake View Road, Desapriya Park, Kolkata     4.5      119.0         500.0
11                 La Pino'z Pizza              Shop 3, E2-4, Ground Floor, Block GP, Sector 5, Salt Lake, Kolkata     4.5      167.0         800.0
12               Pasteleria Bakery        AA 29, 4th Floor, Back Building, Near SAZ Fitness Gym, Kestopur, Kolkata     4.5      152.0         300.0
13   Pramathanath Mistanno Bhandar                           B.T. Road, Near Reliance Mini Store, Sodepur, Kolkata     4.4      131.0         150.0
14         Sunset Resto Bar Lounge                Lytton Hotel, 14 & 14/1, Sudder Street, New Market Area, Kolkata     4.4      198.0        1300.0
15                        Kung Pao                                                 57 A, Park Street Area, Kolkata     4.4      159.0         800.0
16                  The Crepe Cafe                               6/1A, Middleton Street, Park Street Area, Kolkata     4.4       81.0         800.0
17                   Hobbit's Cafe                          42/8A, Gariahat Road, South End Park, Golpark, Kolkata     4.4      201.0         600.0
18               The Canister Cafe                         AG 112, AMP Vaisakhi Mall, Sector 2, Salt Lake, Kolkata     4.4      121.0         300.0
19               Lâinstant CafÃ©                 4/55A, Bijoy Garh Colony, Opposite Axis Bank, Jadavpur, Kolkata     4.4      109.0         800.0
20                     Homely Food                                            P 10, CIT Road, Kankurgachi, Kolkata     4.4       59.0         350.0
21            Calcutta Bakery Cafe                              86/276, Raja S.C Mullick Road, Baghajatin, Kolkata     4.4      135.0         600.0
22                         Hotmenu                                                                   Delivery Only     4.4       78.0         700.0
23            Food Per Square Foot                                          PS Magnum, VIP Road, Kaikhali, Kolkata     4.4      127.0         300.0
24                     Night Ninja                             1/10, Baishnabghata Patuli Township, Garia, Kolkata     4.4       72.0         800.0
25                         Berezia           40A, AJC Bose Road, Opposite Nonapukur Tram Depot, Wellesley, Kolkata     4.3      125.0         250.0
26  Behrouz Biryani - Royal & Safe                              61 A, Sri Aurobindo Road, Golabari, Salkia, Howrah     4.3       44.0         700.0
27               Koyla Cafe Lounge  70, 3rd Floor, Beck Bagan Row, Opposite Quest Mall Gate 5, Ballygunge, Kolkata     4.3       71.0         500.0
28                           Tribe                                        67, Ballygunge Gardens, Golpark, Kolkata     4.3      113.0         600.0
29                 Frosted Delight                                     Rajendra Prasad Colony, Tollygunge, Kolkata     4.3      218.0         400.0
30                        Snaptown                                  Plot 7, CD Block, Sector 1, Salt Lake, Kolkata     4.3      183.0         700.0
31                     Shiv Assram                                          168, Bidhan Sarani, Hatibagan, Kolkata     4.3      154.0         200.0
32                     Tripti Cafe                                       6B, Sultan Alam Road, Tollygunge, Kolkata     4.3      189.0         600.0
33                     Zero Lounge                                                    264, GT Road, Liluah, Howrah     4.3       65.0        1500.0
34                    Desi Chullah                                           308, Kendua Main Road, Garia, Kolkata     4.3      137.0         800.0
35                  Cotts And Coco                       3 Green Park, Block - B, Jessore Road, Lake Town, Kolkata     4.3       48.0         300.0
36             One Sip Restro Cafe  5th Floor, The Terminus, Rajarhat, Beside Pride Plaza Hotel, New Town, Kolkata     4.3      221.0        1200.0

In [68]:
# Q9 - Does popularity affect quality?
 
# Create popularity tiers based on vote_count
df_votes = df[df['voteCount'] > 0].copy()
 
df_votes['popularity_tier'] = pd.cut(
    df_votes['voteCount'],
    bins=[0, 100, 500, 2000, 100000],
    labels=['Low Votes (0-100)', 'Medium (100-500)', 'High (500-2000)', 'Very Popular (2000+)'],
    include_lowest=True
)
 
quality_by_popularity = (
    df_votes[df_votes['rating'].notna()].groupby('popularity_tier', observed=True)
    .agg(
        restaurants=('name', 'count'),
        avg_rating=('rating', 'mean'),
        min_rating=('rating', 'min'),
        max_rating=('rating', 'max')
    )
    .reset_index()
)
 
quality_by_popularity['avg_rating'] = quality_by_popularity['avg_rating'].round(2)
 
print(quality_by_popularity.to_string(index=False))
print("\nInsight: If avg_rating is similar → quality doesn't drop with popularity!")
print("\n")

     popularity_tier  restaurants  avg_rating  min_rating  max_rating
   Low Votes (0-100)         3774        3.25         2.0         4.6
    Medium (100-500)         1057        3.67         2.2         4.8
     High (500-2000)          300        3.94         1.9         4.8
Very Popular (2000+)           59        4.19         3.6         4.9

Insight: If avg_rating is similar → quality doesn't drop with popularity!

In [100]:
# Q10: Best Value Restaurants (Rating per rupee)

value_data = df[
    (df['rating'] >= 3.8) & 
    (df['cost_for_two'].notna()) & 
    (df['cost_for_two'] > 0) &
    (df['voteCount'] > 10)
].copy()
 
# Calculate value score (rating per ₹100)
value_data['value_score'] = value_data['rating'] / (value_data['cost_for_two'] / 100)
 
best_value = value_data.nlargest(55, 'value_score')[
    ['name', 'rating', 'cost_for_two', 'value_score', 'voteCount']
].copy()
 
best_value['cost_for_two'] = best_value['cost_for_two'].astype(int)
best_value['voteCount'] = best_value['voteCount'].astype(int)
best_value['value_score'] = best_value['value_score'].round(2)
print(f"Total Best Value Restaurants found: {len(best_value)}")
print(best_value.to_string(index=False))
print("\nInsight: These restaurants offer excellent quality at reasonable prices!")
print("\n")

Total Best Value Restaurants found: 55
                                    name  rating  cost_for_two  value_score  voteCount
Girish Chandra Dey & Nakur Chandra Nandy     4.8           100         4.80       1586
                        Bhim Chandra Nag     4.3           100         4.30        484
                 Suresh Mistanna Bhander     4.2           100         4.20        214
                               Ping Pong     4.2           100         4.20         30
                          Arun Tea Stall     4.1           100         4.10        467
                          Putiram Sweets     4.1           100         4.10        834
                            Banchharam's     4.1           100         4.10        235
                            Panna Sweets     4.1           100         4.10        326
                Nalin Chandra Das & Sons     4.1           100         4.10        255
                                  Kalika     4.1           100         4.10        523
                                Maharani     4.1           100         4.10        805
                                K.C. Das     4.0           100         4.00        983
              Lakshmi Narayan Shaw & Son     4.0           100         4.00        229
                        Hindustan Sweets     4.0           100         4.00        236
              Sree Hari Mistanna Bhandar     4.0           100         4.00        266
                      Anandamayee Sweets     4.0           100         4.00        165
                              Sharma Tea     3.9           100         3.90        285
                           Shankar Cabin     3.9           100         3.90         67
            Khirki Shri Hari Jalpan Shop     3.9           100         3.90        202
                                   Amrit     3.9           100         3.90         84
                                Gopinath     3.9           100         3.90        200
                Narayan Mistanna Bhandar     3.9           100         3.90        214
                                    Vien     3.8           100         3.80         79
                               Annapurna     3.8           100         3.80         84
                        Shree Paan Dhaba     3.8           100         3.80         96
              Bangasree Misthana Bhandar     3.8           100         3.80        101
                              Panch Bhog     3.8           100         3.80        446
                              Hedua Chat     3.8           100         3.80        139
                             Ghosh & Co.     3.8           100         3.80         39
                                 Mouchak     3.8           100         3.80        164
                        Ujjala Chanachur     3.8           100         3.80         51
                           Haridas Modak     3.8           100         3.80        139
                   Makhan Lal Das & Sons     3.8           100         3.80         67
                                 The Box     3.8           100         3.80         70
                        Dwarik Grandsons     3.8           100         3.80         75
                                   Dehat     3.8           100         3.80        803
                                   Mahua     3.8           100         3.80         92
               Penguin Ice Cream Parlour     3.8           100         3.80         27
           Pramathanath Mistanno Bhandar     4.4           150         2.93        131
                              Kookie Jar     4.3           150         2.87       1071
                            Bombay Kulfi     4.2           150         2.80        340
                            Sankar's Fry     4.2           150         2.80        160
                                 Annaras     4.1           150         2.73        263
                          Haryana Sweets     4.1           150         2.73        288
                                 Campari     4.1           150         2.73        755
                              Kamdhenu's     4.1           150         2.73        164
                        Bonn Tonn Bakery     4.1           150         2.73         81
                                I'm Momo     4.1           150         2.73         99
                Hotel Sidheshwari Ashram     4.0           150         2.67        208
                    Krazy for Chocolates     4.0           150         2.67        177
                        The Cake Counter     4.0           150         2.67        176
                                   Nasta     4.0           150         2.67        254
                  Swissyum Concept Foods     4.0           150         2.67        139
                                 Shibuji     3.9           150         2.60        168
                                Kaka Tea     3.9           150         2.60        214

Insight: These restaurants offer excellent quality at reasonable prices!

In [85]:
# List all the "accident" columns you want to get rid of
cols_to_remove = ['timing_clean', 'timing_status', ]

# 'errors=ignore' prevents the code from crashing if the column is already gone
df.drop(columns=cols_to_remove, errors='ignore', inplace=True)

# Now check your columns again
print(df.columns.tolist())

['name', 'voteCount', 'rating', 'address', 'cusine', 'cost_for_two', 'timing', 'cost_category', 'vote_rank', 'rating_rank', 'segment']

In [86]:
display(df.head(10))

,name,voteCount,rating,address,cusine,cost_for_two,timing,cost_category,vote_rank,rating_rank,segment
0,Peter Cat,12404.0,4.2,"18A, Park Street, Park Street Area, Kolkata","North Indian, Continental",1000.0,11am - 11:20pm,501-1000,1.00,0.97,Premium
1,Naturals Ice Cream,2498.0,4.9,"77/1/A, Ground Floor, Near West Bengal Board, ...","North Indian, Continental",200.0,11am - 12midnight,Under 200,0.99,1.00,Budget
2,Carpe Diem,4083.0,4.4,"18M, Park Street Area, Kolkata",Ice Cream,1000.0,12noon - 12midnight,501-1000,1.00,0.99,Premium
3,Barbeque Nation,5455.0,4.6,"1st Floor, 24, Park Center Building, Park Stre...",Ice Cream,1800.0,"12noon - 3:30pm, 6:30pm - 10:45pm",1001-2000,1.00,1.00,Luxury
4,Flurys,4709.0,4.2,"15, Apeejay House, Park Street Area, Kolkata","Chinese, North Indian, Continental",400.0,7:30am - 11pm,201-500,1.00,0.97,Mid-Range
5,KFC,2135.0,4.1,"20K, Park Street, Park Street Area, Kolkata","Chinese, North Indian, Continental",450.0,11am - 11pm,201-500,0.99,0.95,Mid-Range
6,Tung Fong,3644.0,4.3,"25 B, Ground Floor, Karnani Mansion, Free Scho...","North Indian, Chinese, Kebab, BBQ",1000.0,"12noon - 4pm, 6pm - 11pm",501-1000,1.00,0.98,Premium
7,Arsalan,1500.0,4.0,"119 A, Muzaffar Ahmed Street, Mirza Ghalib Str...","North Indian, Chinese, Kebab, BBQ",1000.0,11am - 11:45pm,501-1000,0.98,0.92,Premium
8,Kusum Rolls,1973.0,4.1,"21, Karnani Mansion, Park Street Area, Kolkata","Bakery, Desserts, Sandwich",300.0,12noon - 11pm,201-500,0.99,0.95,Budget
9,Kareem's,1027.0,4.3,"55 B, Mirza Ghalib Street, Park Street Area, K...","Bakery, Desserts, Sandwich",1200.0,"12:30pm - 4:30pm, 6:30pm - 11:30pm",1001-2000,0.97,0.98,Premium

## 8. NumPy Deep Statistical Analysis
*Pure NumPy operations — mean, median, std, percentile*

In [70]:
# NumPy arrays from cleaned data
ratings_arr = np.array(df['rating'].dropna())
cost_arr    = np.array(df['cost_for_two'].dropna())
votes_arr   = np.array(df['voteCount'].dropna())

print('=' * 50)
print('  NUMPY — RATING STATISTICS')
print('=' * 50)
print('Total restaurants :', len(ratings_arr))
print('Mean rating       :', round(np.mean(ratings_arr), 2))
print('Median rating     :', round(np.median(ratings_arr), 2))
print('Std deviation     :', round(np.std(ratings_arr), 2))
print('Variance          :', round(np.var(ratings_arr), 2))
print('Min rating        :', round(np.min(ratings_arr), 1))
print('Max rating        :', round(np.max(ratings_arr), 1))
print('25th percentile   :', np.percentile(ratings_arr, 25))
print('50th percentile   :', np.percentile(ratings_arr, 50))
print('75th percentile   :', np.percentile(ratings_arr, 75))
print('IQR               :', round(
    np.percentile(ratings_arr, 75) - np.percentile(ratings_arr, 25), 2))

==================================================
  NUMPY — RATING STATISTICS
==================================================
Total restaurants : 5198
Mean rating       : 3.39
Median rating     : 3.4
Std deviation     : 0.41
Variance          : 0.16
Min rating        : 1.9
Max rating        : 4.9
25th percentile   : 3.1
50th percentile   : 3.4
75th percentile   : 3.6
IQR               : 0.5

In [71]:
print('=' * 50)
print('  NUMPY — COST FOR TWO STATISTICS')
print('=' * 50)
print('Mean cost         : Rs.', round(np.mean(cost_arr)))
print('Median cost       : Rs.', round(np.median(cost_arr)))
print('Std deviation     : Rs.', round(np.std(cost_arr)))
print('Min cost          : Rs.', int(np.min(cost_arr)))
print('Max cost          : Rs.', int(np.max(cost_arr)))
print('25th percentile   : Rs.', np.percentile(cost_arr, 25))
print('75th percentile   : Rs.', np.percentile(cost_arr, 75))
print('90th percentile   : Rs.', np.percentile(cost_arr, 90))

print('\n' + '=' * 50)
print('  NUMPY — VOTES STATISTICS')
print('=' * 50)
print('Mean votes        :', round(np.mean(votes_arr)))
print('Median votes      :', round(np.median(votes_arr)))
print('Max votes         :', int(np.max(votes_arr)))
print('Std deviation     :', round(np.std(votes_arr)))

==================================================
  NUMPY — COST FOR TWO STATISTICS
==================================================
Mean cost         : Rs. 409
Median cost       : Rs. 300
Std deviation     : Rs. 328
Min cost          : Rs. 100
Max cost          : Rs. 4500
25th percentile   : Rs. 250.0
75th percentile   : Rs. 500.0
90th percentile   : Rs. 700.0

==================================================
  NUMPY — VOTES STATISTICS
==================================================
Mean votes        : 155
Median votes      : 34
Max votes         : 12404
Std deviation     : 436

In [72]:
# NumPy where — classify restaurants as budget, mid, premium
cost_arr_full = np.array(df['cost_for_two'])

segment = np.where(cost_arr_full <= 300,   'Budget',
          np.where(cost_arr_full <= 800,   'Mid-Range',
          np.where(cost_arr_full <= 1500,  'Premium',
                                           'Luxury')))

df['segment'] = segment

unique, counts = np.unique(segment, return_counts=True)

print('=' * 45)
print('  NUMPY WHERE — RESTAURANT SEGMENTS')
print('=' * 45)
for seg, cnt in zip(unique, counts):
    pct = round(cnt / len(segment) * 100, 1)
    bar = '█' * int(pct / 2)
    print(seg.ljust(12), str(cnt).rjust(5),
          'restaurants', str(pct).rjust(5), '%', bar)

=============================================
  NUMPY WHERE — RESTAURANT SEGMENTS
=============================================
Budget        2675 restaurants  51.5 % █████████████████████████
Luxury          62 restaurants   1.2 %
Mid-Range     2230 restaurants  42.9 % █████████████████████
Premium        231 restaurants   4.4 % ██

In [159]:
# Customer engagement pattern

print("\n" + "="*50)
print("  NUMPY — CUSTOMER ENGAGEMENT PATTERNS")
print("="*50)

votes_arr = np.array(df['voteCount'].dropna())

# Engagement Tiers
super_popular = np.sum(votes_arr > 2000)
niche = np.sum(votes_arr < 100)
average = np.sum((votes_arr >= 100) & (votes_arr <= 2000))

print(f"\n🔥 Super Popular (>2,000 votes): {super_popular} restaurants")
print(f"📍 Niche (<100 votes):          {niche} restaurants")
print(f"📊 Average (100-2,000 votes):   {average} restaurants")

# Percentage breakdown
total_rated = len(votes_arr)
print(f"\nBreakdown (out of {total_rated} restaurants with votes):")
print(f"  Super Popular: {(super_popular/total_rated*100):.1f}%")
print(f"  Niche:        {(niche/total_rated*100):.1f}%")
print(f"  Average:      {(average/total_rated*100):.1f}%")

print(f"\nInsight: Top {super_popular} restaurants get majority of votes!")

==================================================
  NUMPY — CUSTOMER ENGAGEMENT PATTERNS
==================================================

🔥 Super Popular (>2,000 votes): 59 restaurants
📍 Niche (<100 votes):          3772 restaurants
📊 Average (100-2,000 votes):   1367 restaurants

Breakdown (out of 5198 restaurants with votes):
  Super Popular: 1.1%
  Niche:        72.6%
  Average:      26.3%

Insight: Top 59 restaurants get majority of votes!